### ISSUE TITLE
Please publish on NPM

### ISSUE THREAD

**Issue by GiorgioAresu** [janober/loopback-connector-couchbase-expert#7]
Hi, after struggling with the library I was thinking about making a fork and merge some PR, but fortunately I looked at all the forks and found yours, the only one active.
Considering that the original developer has been inactive for 4 years, not even accepting PRs, could you publish this as a new npm package? This would greatly improve discoverability and reduce duplicate work like I was going to do. Thanks

**Comment by janober** [comment]
Hi!
Yes, I could publish it but is this fork really what you are looking for? It is specifically made to not use N1QL and only work with ids. So you can not use "Model.find()" you can only use "Mode.findById". The same with delete. Everything else will not work.

**Comment by GiorgioAresu** [comment]
Oh, nevermind then, I guess I have no choice but to fork the original.
Thank you anyway :)

**Comment by janober** [comment]
Yes, that makes probably the most sense when you need N1QL. Have a nice day!
